checks:
    javascript: true

filter:
    excluded_paths:
        - node_modules/*
        - static/*
        - views/*

build:
    environment:
        node: '8.6.0'
        mongodb: '3.2'
    tests:
        override:
            -
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'build2/coverage/clover.xml'
                    format: 'clover'
