checks:
    javascript: true

filter:
    excluded_paths:
        - node_modules/*
        - coverage/*
        - static/*
        - views/*

    tests:
        override:
            -
                command: 'npm test-scrutinizer'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
