checks:
    javascript: true

build:
    nodes:
        analysis:
            environment:
                node:
                    version: 8.9.1
        tests: true
    environment:
        mongodb: '3.2'
        node: 9.2.1
    dependencies:

    tests:
        override:
            -
                command: 'npm run test-scrutinizer'
                coverage:
                    file: 'build/coverage/clover.xml'
                    format: 'clover'
